// discord-bot/ipfs.js
// w3up (web3.storage / Storacha) upload helper for Node.js.
//
// This mirrors the pattern used in js/w3upClient.js but runs in Node where
// there is no browser window.  It uses a server-side agent key + UCAN proof
// so the bot can upload without interactive email login.
//
// Required env vars (via config.js):
//   W3UP_KEY   — base64url-encoded ed25519 private key generated by `w3 key create`
//   W3UP_PROOF — base64url-encoded UCAN proof delegating `store/add` + `upload/add`
//                to the agent key above, generated by `w3 delegation create`

import { create } from '@web3-storage/w3up-client';
import { StoreMemory } from '@web3-storage/w3up-client/stores/memory';
import * as Proof from '@web3-storage/w3up-client/proof';
import { Signer } from '@web3-storage/w3up-client/principal/ed25519';

/**
 * Build and authorise a w3up client using a pre-issued UCAN delegation.
 *
 * @param {string} encodedKey   - base64url ed25519 private key (W3UP_KEY)
 * @param {string} encodedProof - base64url UCAN proof (W3UP_PROOF)
 * @returns {Promise<import('@web3-storage/w3up-client').Client>}
 */
async function buildClient(encodedKey, encodedProof) {
  const principal = Signer.parse(encodedKey);
  const store     = new StoreMemory();
  const client    = await create({ principal, store });

  const proof = await Proof.parse(encodedProof);
  const space = await client.addSpace(proof);
  await client.setCurrentSpace(space.did());

  return client;
}

/**
 * Upload a Buffer (or Uint8Array) to IPFS via w3up.
 *
 * @param {Buffer|Uint8Array} buffer   - File contents
 * @param {string}            filename - Name given to the file (used by w3up)
 * @param {string}            mimeType - MIME type (e.g. "audio/mpeg")
 * @param {string}            encodedKey
 * @param {string}            encodedProof
 * @returns {Promise<string>} ipfs:// URI of the uploaded file
 */
export async function uploadToIPFS(buffer, filename, mimeType, encodedKey, encodedProof) {
  const client = await buildClient(encodedKey, encodedProof);

  // w3up expects a File-like object with a name and stream() / arrayBuffer()
  const file = new File([buffer], filename, { type: mimeType });
  const cid  = await client.uploadFile(file);

  return `ipfs://${cid}`;
}
